// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: process.env["DATABASE_URL"],       // Supabase connection pooler (Transaction mode)
    // directUrl é configurado em schema.prisma via env("DIRECT_URL") — Prisma 7 não suporta no config
  },
});
