export const Routes = {
  HOME: '/',
  LOGIN: '/login',
  INVITE: (token: string) => `/invite/${token}`,
  RESET_PASSWORD: '/auth/reset-password',
  DASHBOARD: '/dashboard',
  RADAR: '/radar',
  LEADS: '/leads',
  LEAD_DETAIL: (id: string) => `/leads/${id}`,
  COLETAS: '/coletas',
  COLLECTION_DETAIL: (id: string) => `/coletas/${id}`,
  EXPORTAR: '/exportar',
  EXPORT: '/exportar',
  PERFIL: '/perfil',
  ADMIN: '/admin',
  ADMIN_CONVITES: '/admin/convites',
  ADMIN_CONFIGURACOES: '/admin/configuracoes',
  ADMIN_SCORING: '/admin/scoring',
  ADMIN_METRICAS: '/admin/metricas',
  ADMIN_AUDIT_LOG: '/admin/audit-log',
  ADMIN_CONFIG_REGIONS:  '/admin/config/regions',
  ADMIN_CONFIG_NICHES:   '/admin/config/niches',
  ADMIN_CONFIG_LIMITS:   '/admin/config/limits',
  ADMIN_CONFIG_SCRAPERS: '/admin/config/scrapers',
  ADMIN_CONFIG_SCORING:  '/admin/config/scoring',
  ADMIN_USERS: '/admin/users',
  ONBOARDING: '/onboarding',
} as const

export const API_ROUTES = {
  AUTH_LOGIN: '/api/v1/auth/login',
  AUTH_LOGOUT: '/api/v1/auth/logout',
  AUTH_RESET_PASSWORD: '/api/v1/auth/reset-password',
  AUTH_UPDATE_PASSWORD: '/api/v1/auth/update-password',
  PROFILE: '/api/v1/profile',
  PROFILE_DELETION: '/api/v1/profile/deletion-request',
  PROFILE_DATA_EXPORT: '/api/v1/profile/data-export',
  INVITES_PUBLIC: (token: string) => `/api/v1/invites/${token}`,
  INVITES_ACTIVATE: (token: string) => `/api/v1/invites/${token}/activate`,
  ADMIN_INVITES: '/api/v1/admin/invites',
  ADMIN_INVITE: (id: string) => `/api/v1/admin/invites/${id}`,
  ADMIN_INVITE_RESEND: (id: string) => `/api/v1/admin/invites/${id}/resend`,
  LEADS: '/api/v1/leads',
  LEADS_COUNT: '/api/v1/leads/count',
  LEADS_EXPORT: '/api/v1/leads/export',
  LEAD_BUDGETFLOW_EXPORT: (id: string) => `/api/v1/leads/${id}/export/budgetflow`,
  RADAR: '/api/v1/radar',
  RADAR_PRESETS: '/api/v1/radar/presets',
  RADAR_RECOLLECT: '/api/v1/radar/recollect',
  LEAD: (id: string) => `/api/v1/leads/${id}`,
  LEAD_STATUS: (id: string) => `/api/v1/leads/${id}/status`,
  LEAD_NOTES: (id: string) => `/api/v1/leads/${id}/notes`,
  LEAD_PITCH: (id: string) => `/api/v1/leads/${id}/pitch`,
  PITCH_TEMPLATES: '/api/v1/pitch-templates',
  LEAD_FALSE_POSITIVE: (id: string) => `/api/v1/leads/${id}/false-positive`,
  JOBS: '/api/v1/jobs',
  JOBS_QUOTA: '/api/v1/jobs/quota',
  JOB: (id: string) => `/api/v1/jobs/${id}`,
  JOB_STATUS: (id: string) => `/api/v1/jobs/${id}/status`,
  ADMIN_CREDENTIALS: '/api/v1/admin/config/credentials',
  ADMIN_CREDENTIAL: (provider: string) => `/api/v1/admin/config/credentials/${provider}`,
  ADMIN_SCORING_RULES: '/api/v1/admin/config/scoring-rules',
  ADMIN_SCORING_RULE: (id: string) => `/api/v1/admin/config/scoring-rules/${id}`,
  ADMIN_SCORING_RESET: '/api/v1/admin/config/scoring-rules/reset',
  ADMIN_CONFIG_REGIONS:  '/api/v1/admin/config/regions',
  ADMIN_CONFIG_REGION:   (id: string) => `/api/v1/admin/config/regions/${id}`,
  ADMIN_CONFIG_NICHES:   '/api/v1/admin/config/niches',
  ADMIN_CONFIG_NICHE:    (id: string) => `/api/v1/admin/config/niches/${id}`,
  ADMIN_CONFIG_LIMITS:   '/api/v1/admin/config/limits',
  ADMIN_CONFIG_PROVIDERS:'/api/v1/admin/config/providers',
  ADMIN_AUDIT_LOG:       '/api/v1/admin/audit-log',
  ADMIN_AUDIT_LOG_EXPORT:'/api/v1/admin/audit-log/export',
  ONBOARDING_COMPLETE: '/api/v1/onboarding/complete',
  ONBOARDING_PROGRESS: '/api/v1/onboarding/progress',
  ONBOARDING_CATALOG: '/api/v1/onboarding/catalog',
  HEALTH: '/api/health',
} as const
