export const Routes = {
  HOME: '/',
  LOGIN: '/login',
  INVITE: (token: string) => `/invite/${token}`,
  RESET_PASSWORD: '/auth/reset-password',
  DASHBOARD: '/dashboard',
  LEADS: '/leads',
  LEAD_DETAIL: (id: string) => `/leads/${id}`,
  COLETAS: '/coletas',
  COLLECTION_DETAIL: (id: string) => `/coletas/${id}`,
  EXPORTAR: '/exportar',
  EXPORT: '/exportar',
  PERFIL: '/perfil',
  ADMIN: '/admin',
  ADMIN_CONVITES: '/admin/convites',
  ADMIN_CONFIGURACOES: '/admin/configuracoes',
  ADMIN_SCORING: '/admin/scoring',
  ADMIN_METRICAS: '/admin/metricas',
  ONBOARDING: '/onboarding',
} as const

export const API_ROUTES = {
  AUTH_LOGIN: '/api/v1/auth/login',
  AUTH_LOGOUT: '/api/v1/auth/logout',
  AUTH_RESET_PASSWORD: '/api/v1/auth/reset-password',
  AUTH_UPDATE_PASSWORD: '/api/v1/auth/update-password',
  PROFILE: '/api/v1/profile',
  PROFILE_DELETION: '/api/v1/profile/deletion-request',
  PROFILE_DATA_EXPORT: '/api/v1/profile/data-export',
  INVITES_PUBLIC: (token: string) => `/api/v1/invites/${token}`,
  INVITES_ACTIVATE: (token: string) => `/api/v1/invites/${token}/activate`,
  ADMIN_INVITES: '/api/v1/admin/invites',
  ADMIN_INVITE: (id: string) => `/api/v1/admin/invites/${id}`,
  ADMIN_INVITE_RESEND: (id: string) => `/api/v1/admin/invites/${id}/resend`,
  LEADS: '/api/v1/leads',
  LEADS_COUNT: '/api/v1/leads/count',
  LEADS_EXPORT: '/api/v1/leads/export',
  LEAD: (id: string) => `/api/v1/leads/${id}`,
  LEAD_STATUS: (id: string) => `/api/v1/leads/${id}/status`,
  LEAD_NOTES: (id: string) => `/api/v1/leads/${id}/notes`,
  LEAD_PITCH: (id: string) => `/api/v1/leads/${id}/pitch`,
  LEAD_FALSE_POSITIVE: (id: string) => `/api/v1/leads/${id}/false-positive`,
  JOBS: '/api/v1/jobs',
  JOB: (id: string) => `/api/v1/jobs/${id}`,
  JOB_STATUS: (id: string) => `/api/v1/jobs/${id}/status`,
  ADMIN_CREDENTIALS: '/api/v1/admin/config/credentials',
  ADMIN_CREDENTIAL: (provider: string) => `/api/v1/admin/config/credentials/${provider}`,
  ADMIN_SCORING_RULES: '/api/v1/admin/config/scoring-rules',
  ADMIN_SCORING_RULE: (id: string) => `/api/v1/admin/config/scoring-rules/${id}`,
  ADMIN_SCORING_RESET: '/api/v1/admin/config/scoring-rules/reset',
  ONBOARDING_COMPLETE: '/api/v1/onboarding/complete',
  HEALTH: '/api/health',
} as const
